name: flowru_client
description: Flowru client loyalty app
publish_to: "none"

version: 1.0.3+33
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter:
    sdk: flutter

  http: ^1.2.2
  shared_preferences: ^2.3.2
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  particles_flutter: ^1.0.0
  url_launcher: ^6.3.2
  app_links: ^6.4.0
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/flowru_logo.png
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
